# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='books',
        ),
        migrations.AddField(
            model_name='reviews',
            name='books',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt_reviewer.Books'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='users',
        ),
        migrations.AddField(
            model_name='reviews',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt_reviewer.Users'),
            preserve_default=False,
        ),
    ]
